backend:
  name: github
  repo: TRegourd/www-LMDC
  branch: master
media_folder: src/assets/image
public_folder: assets/image
publish_mode: editorial_workflow
collections:
  - label: "Contenu de la page d'accueil"
    name: "index"
    files:
      - label: "Bannière d'accueil"
        name: "heroContent"
        file: "src/content/hero.md"
        fields:
          - { label: Titre, name: title, widget: string }
          - { label: Sous-Titre, name: subtitle, widget: string }
          - { label: Image, name: hero_img, widget: image }
          - { label: Carte Glissante Haute, name: topCard, widget: string }
          - { label: Carte Glissante Basse, name: botCard, widget: string }

  - label: "Contenu de la FAQ"
    name: "faq"
    files:
      - label: "Contenu de la page"
        name: "faqContent"
        file: "src/content/faq.md"
        fields:
          - { label: Titre, name: title, widget: string }
          - { label: Sous Titre, name: subtitle, widget: string }
          - label: Questions
            name: questions
            widget: list
            fields:
              - { label: Titre, name: name, widget: string }
              - { label: Texte, name: text, widget: markdown }
              - {
                  label: Catégorie,
                  name: category,
                  widget: "select",
                  options: ["Général", "Fiscalité", "Investissement"],
                  required: true,
                }
