backend:
  name: github
  repo: TRegourd/www-LMDC
  branch: master
media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow
collections:
  - label: "Contenu de la page d'accueil"
    name: "index"
    files:
      - label: "Cours des Cryptos"
        name: "indexCrypto"
        file: "src/content/indexCrypto.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
